# Generated by Django 5.0.1 on 2024-08-04 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 19, 55, 13, 715436)),
        ),
    ]
